// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.communication.phonenumbers.siprouting.models;

import com.azure.core.annotation.Fluent;

/** Represents a SIP trunk for routing calls. See RFC 4904. */
@Fluent
public final class SipTrunk {
    /*
     * Gets or sets FQDN of the trunk.
     */
    private String fqdn;
    /*
     * Gets or sets SIP signaling port of the trunk.
     */
    private int sipSignalingPort;

    /**
     * Get the fqdn property: Gets or sets FQDN of the trunk.
     *
     * @return the fqdn value.
     */
    public String getFqdn() {
        return this.fqdn;
    }

    /**
     * Set the fqdn property: Gets or sets FQDN of the trunk.
     *
     * @param fqdn the fqdn value to set.
     * @return the Trunk object itself.
     */
    public SipTrunk setFqdn(String fqdn) {
        this.fqdn = fqdn;
        return this;
    }

    /**
     * Get the sipSignalingPort property: Gets or sets SIP signaling port of the trunk.
     *
     * @return the sipSignalingPort value.
     */
    public int getSipSignalingPort() {
        return this.sipSignalingPort;
    }

    /**
     * Set the sipSignalingPort property: Gets or sets SIP signaling port of the trunk.
     *
     * @param sipSignalingPort the sipSignalingPort value to set.
     * @return the Trunk object itself.
     */
    public SipTrunk setSipSignalingPort(int sipSignalingPort) {
        this.sipSignalingPort = sipSignalingPort;
        return this;
    }
}
